import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 🚨 ၁။ စောစောက ဆောက်ထားတဲ့ Providers ဖိုင်ကို Import ခေါ်ပါမည်
import { Providers } from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 🚨 ၂။ ဤနေရာတွင် {children} အား Providers ဖြင့် အုပ်ပေးလိုက်ပါသည် */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}